import { Chapter, StateAbbreviation, StateConfig } from '../types/map';

const STATES: Record<StateAbbreviation, StateConfig> = {
  AL: { fill: '#4EC2BA' },
  AK: { fill: '#FEEA53' },
  AZ: { fill: '#D4D2D1' },
  AR: { fill: '#F48F87' },
  CA: { fill: '#4EC2BA' },
  CO: { fill: '#FEEA53' },
  CT: { fill: '#D4D2D1' },
  DE: { fill: '#F48F87' },
  FL: { fill: '#4EC2BA' },
  GA: { fill: '#FEEA53' },
  HI: { fill: '#D4D2D1' },
  ID: { fill: '#F48F87' },
  IL: { fill: '#4EC2BA' },
  IN: { fill: '#FEEA53' },
  IA: { fill: '#D4D2D1' },
  KS: { fill: '#F48F87' },
  KY: { fill: '#4EC2BA' },
  LA: { fill: '#FEEA53' },
  ME: { fill: '#D4D2D1' },
  MD: { fill: '#F48F87' },
  MA: { fill: '#4EC2BA' },
  MI: { fill: '#FEEA53' },
  MN: { fill: '#D4D2D1' },
  MS: { fill: '#F48F87' },
  MO: { fill: '#4EC2BA' },
  MT: { fill: '#FEEA53' },
  NE: { fill: '#D4D2D1' },
  NV: { fill: '#F48F87' },
  NH: { fill: '#4EC2BA' },
  NJ: { fill: '#FEEA53' },
  NM: { fill: '#D4D2D1' },
  NY: { fill: '#F48F87' },
  NC: { fill: '#4EC2BA' },
  ND: { fill: '#FEEA53' },
  OH: { fill: '#D4D2D1' },
  OK: { fill: '#F48F87' },
  OR: { fill: '#4EC2BA' },
  PA: { fill: '#FEEA53' },
  RI: { fill: '#D4D2D1' },
  SC: { fill: '#F48F87' },
  SD: { fill: '#4EC2BA' },
  TN: { fill: '#FEEA53' },
  TX: { fill: '#D4D2D1' },
  UT: { fill: '#F48F87' },
  VT: { fill: '#4EC2BA' },
  VA: { fill: '#FEEA53' },
  WA: { fill: '#D4D2D1' },
  WV: { fill: '#F48F87' },
  WI: { fill: '#4EC2BA' },
  WY: { fill: '#FEEA53' },
};

const CHAPTER_DATA: Chapter[] = [
  { id: 1, city: 'Boise', state: 'ID', isAcceptingRequests: true },
  { id: 2, city: 'Reno', state: 'NV', isAcceptingRequests: true },
  { id: 3, city: 'Phoenix', state: 'AZ', isAcceptingRequests: true },
  { id: 4, city: 'Denver Metro', state: 'CO', isAcceptingRequests: true },
  { id: 5, city: 'Fargo', state: 'ND', isAcceptingRequests: true },
  { id: 6, city: 'Minot', state: 'ND', isAcceptingRequests: true },
  { id: 7, city: 'Oklahoma City', state: 'OK', isAcceptingRequests: true },
  { id: 8, city: 'Iowa City', state: 'IA', isAcceptingRequests: true },
  { id: 9, city: 'Northwest', state: 'AR', isAcceptingRequests: true },
  { id: 10, city: 'Columbia County', state: 'WI', isAcceptingRequests: false },
  { id: 11, city: 'DeForest', state: 'WI', isAcceptingRequests: true },
  { id: 12, city: 'Madison', state: 'WI', isAcceptingRequests: true },
  { id: 13, city: 'Sun Prairie', state: 'WI', isAcceptingRequests: true },
  { id: 14, city: 'Janesville', state: 'WI', isAcceptingRequests: true },
  { id: 15, city: 'Monroe', state: 'WI', isAcceptingRequests: true },
  { id: 16, city: 'Aurora', state: 'IL', isAcceptingRequests: true },
  { id: 17, city: 'Grand Rapids', state: 'MI', isAcceptingRequests: true },
  { id: 18, city: 'Lexington', state: 'KY', isAcceptingRequests: true },
  { id: 19, city: 'Mobile', state: 'AL', isAcceptingRequests: true },
  { id: 20, city: 'Cumming', state: 'GA', isAcceptingRequests: true },
  { id: 21, city: 'Palm Beach County', state: 'FL', isAcceptingRequests: true },
  { id: 22, city: 'Philadelphia', state: 'PA', isAcceptingRequests: true },
  { id: 23, city: 'Syracuse', state: 'NY', isAcceptingRequests: true },
  { id: 24, city: 'Boonsboro', state: 'MD', isAcceptingRequests: true },
  { id: 25, city: 'Carroll County', state: 'MD', isAcceptingRequests: true },
];

const StateAbbreviationToState: Record<StateAbbreviation, string> = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};

export { CHAPTER_DATA, STATES, StateAbbreviationToState };
